apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-streaming
spec:
  strategy: streaming
  collector:
    options:
      kafka:
        producer:
          topic: jaeger-spans
          # Note: This assumes kafka is running in the "project1" namespace.
          brokers: my-cluster-kafka-brokers.project1:9092
  ingester:
    options:
      kafka:
        consumer:
          topic: jaeger-spans
          brokers: my-cluster-kafka-brokers.project1:9092
      ingester:
        deadlockInterval: 0
  storage:
    type: elasticsearch
    options:
      es:
        # Note: This assumes elasticsearch is running in the "project1" namespace.
        server-urls: http://elasticsearch.project1.svc:9200
